{
 "title": "Qualtrics Event GW",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "In Flight Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "in_flight_requests{job=\"qualtrics-event-gw-management\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests_processed_total{job=\"qualtrics-event-gw-management\"}[1m])) by (responseCode)",
     "legendFormat": "{{responseCode}}"
    }
   ]
  },
  {
   "title": "Avg Server Response Time (Mills)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "  avg(rate(server_response_time_sum[1m])/rate(server_response_time_count[1m]))/1000000",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Memory Allocation Qualtrics Event Gateway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name=\"qualtrics-event-gw\"}/1048576 ",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg(container_spec_memory_limit_bytes{container_name=\"qualtrics-event-gw\"}) /1048576",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Avg Client Response Times (Mills)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(client_response_time_sum[1m])/rate(client_response_time_count[1m]))/1000000",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Memory Allocation KNATIVE Publisher",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name=\"publish-knative\"}/1048576",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg(container_spec_memory_limit_bytes{container_name=\"publish-knative\"}) /1048576",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Container Readiness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{container=\"qualtrics-event-gw\"})",
     "legendFormat": "Number of Containers"
    }
   ]
  }
 ]
}