apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}
type: Opaque
data:
  headers: {{ .Values.headers | b64enc }}
  formparameters: {{ .Values.formparameters | b64enc }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bundle.fullname" . }}
        component: {{ template "bundle.fullname" . }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: {{ template "bundle.fullname" . }}
        image: "jcawley5/kyma-oauth-proxy"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        envFrom:
          - secretRef:
              name: {{ template "bundle.fullname" . }}
              optional: false
        args:
          - --requestBodyForm=$(formparameters)
          - --headers=$(headers)
          - --oauthURL={{ .Values.oauth_url }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.oAuthProxyName }}-{{ .Values.application_name }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}
spec:
  selector:
    component: {{ template "bundle.fullname" . }}
  ports:
    - port: 8080
      name: http