apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: qualtrics-event-gw
  labels:
     app: qualtrics-event-gw
spec:
  hostname: qualtrics-event
  service:
    name: qualtrics-event-gw
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:    
     app: qualtrics-event-gw
  name: qualtrics-event-gw
spec:
  selector:
    app: qualtrics-event-gw
  ports:
  - name: http
    port: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qualtrics-event-gw
  name: qualtrics-event-gw-management
spec:
  selector:
    app: qualtrics-event-gw
  ports:
    - name: management
      port: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualtrics-event-gw
  labels:
    app: qualtrics-event-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualtrics-event-gw
  template:
    metadata:
      labels:
        app: qualtrics-event-gw
      annotations:
        traffic.sidecar.istio.io/includeInboundPorts: "8080"
    spec:
      containers:
      - name: qualtrics-event-gw
        image: andy008/qualtrics-event-gw:0.0.5
        imagePullPolicy: "Always"
        args: 
         - "-kyma-eventurl"
         - $(kyma-eventurl)
         - "-applicationname"
         - $(application-name)
         - "-hmac-key"
         - $(hmac_key)
         - "-hmac"
         - "-topic-conf"
         - "conf/topic_config.json"
         - "-log-level"
         - "ERROR"
         - "timeout"
         - $(timeout-mil)
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: management
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          periodSeconds: 30
          initialDelaySeconds: 5
          failureThreshold: 1
          successThreshold: 1
        env:
        - name: hmac_key
          valueFrom:
            secretKeyRef:
              name: qualtrics-event-gw-hmac
              key: sharedkey
        - name: application-name
          valueFrom:
            configMapKeyRef:
              name: qualtrics-event-gw-params
              key: application-name
        - name: timeout-mil
          valueFrom:
            configMapKeyRef:
              name: qualtrics-event-gw-params
              key: timeout-mil
        - name: kyma-eventurl
          valueFrom:
            configMapKeyRef:
              name: qualtrics-event-gw-params
              key: kyma-eventurl
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 5Mi
        volumeMounts:
          - mountPath: /conf
            name: configuration
            readOnly: true
      volumes:
        - name: configuration
          configMap:
            name: qualtrics-event-gw-config
---
apiVersion: v1
kind: Secret
metadata:
  name: qualtrics-event-gw-hmac
type: Opaque
data:
  sharedkey: {base64key}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qualtrics-event-gw-params
  labels:
    app: qualtrics-event-gw
data:
  application-name: "{app-name}"
  timeout-mil: "2000"
  kyma-eventurl: "http://event-bus-publish.kyma-system.svc.cluster.local:8080/v1/events"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: qualtrics-event-gw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qualtrics-event-gw
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70